# Generated by Django 6.0.6 on 2026-06-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(db_column='activity_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('exam', 'Examen'), ('quiz', 'Quiz'), ('project', 'Proyecto'), ('homework', 'Tarea'), ('presentation', 'Presentación')], max_length=100)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completada'), ('postponed', 'Postergada'), ('overdue', 'Vencida')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(db_column='subtask_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='', help_text='Nota opcional al posponer o cambiar estado', null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completada'), ('postponed', 'Postergada'), ('overdue', 'Vencida')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'subtask',
            },
        ),
    ]
