# Generated by Django 6.0.6 on 2026-06-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Nota opcional al posponer o cambiar estado'),
        ),
    ]
